POST http://localhost:8000/api/users/login?name=contoh
Content-Type: application/json

{
  "username" : "nurdin",
  "password" : "nurdin"
}

###

GET http://localhost:8000/api/users/current
x-username: 4